"""
Django settings for sistem_logistik project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# For production, move this to environment variable
SECRET_KEY = 'django-insecure-i8^(oxotkvkqbi#ety6&^9jsar4)@++tkm1!*zdmezz)58zml4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ['axis-pasture-canopy.ngrok-free.dev', 'localhost', '127.0.0.1']  # Untuk pengembangan, izinkan semua host. Sesuaikan untuk produksi.
# ALLOWED_HOSTS = ['web-production-a7b8a3.up.railway.app']
import os
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    'logistik',  # Tambahkan aplikasi logistik ke INSTALLED_APPS
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'sistem_logistik.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistem_logistik.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_logistik',           # Sesuaikan dengan nama database
        'USER': 'postgres',              # Sesuaikan dengan user PostgreSQL
        'PASSWORD': 'admin',             # Sesuaikan dengan password PostgreSQL
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# --- PENGATURAN LOKALISASI (INDONESIA) ---
LANGUAGE_CODE = 'id-id'        # Mengubah bahasa sistem error/admin menjadi Bahasa Indonesia
TIME_ZONE = 'Asia/Jakarta'     # Mengubah zona waktu dari UTC menjadi WIB (GMT+7)

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Pengaturan untuk menyimpan file gambar (Media)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Pengaturan URL untuk Login dan Logout
#LOGIN_URL = 'http://localhost:8000/login/' # Mengarahkan user yang belum login ke halaman ini
#LOGIN_REDIRECT_URL = 'http://localhost:8000/admin/' # Ganti 'scanner' dengan nama path URL halaman scan Anda
#LOGOUT_REDIRECT_URL = 'http://localhost:8000/login/' # Setelah logout, kembalikan ke halaman login

# Pengaturan URL untuk Login dan Logout (Gunakan Jalur Relatif)
LOGIN_URL = '/login/' 
LOGIN_REDIRECT_URL = '/admin/'  # Jika role default lari ke admin
LOGOUT_REDIRECT_URL = '/login/'

# Karena kamu menggunakan POST request untuk form/scanner, tambahkan ini agar tidak error CSRF (harus pakai https://)
CSRF_TRUSTED_ORIGINS = ['https://axis-pasture-canopy.ngrok-free.dev']
