# Generated by Django 5.2.12 on 2026-03-12 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lokasi', models.CharField(max_length=100)),
                ('jenis_lokasi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LotProduksi',
            fields=[
                ('id_lot', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_masuk', models.DateField(auto_now_add=True)),
                ('qty_awal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status_aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterBarang',
            fields=[
                ('kode_barang', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=50)),
                ('satuan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LogTraceability',
            fields=[
                ('id_log', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waktu_scan', models.DateTimeField(auto_now_add=True)),
                ('user_scanner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('lokasi_asal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_keluar', to='logistik.lokasi')),
                ('lokasi_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_masuk', to='logistik.lokasi')),
                ('id_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistik.lotproduksi')),
            ],
        ),
        migrations.AddField(
            model_name='lotproduksi',
            name='kode_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistik.masterbarang'),
        ),
    ]
