# Generated by Django 5.2.12 on 2026-03-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logtraceability',
            options={'verbose_name_plural': 'Log Traceability'},
        ),
        migrations.AlterModelOptions(
            name='lokasi',
            options={'verbose_name_plural': 'Lokasi'},
        ),
        migrations.AlterModelOptions(
            name='lotproduksi',
            options={'verbose_name_plural': 'Lot Produksi'},
        ),
        migrations.AlterModelOptions(
            name='masterbarang',
            options={'verbose_name_plural': 'Master Barang'},
        ),
        migrations.RemoveField(
            model_name='lotproduksi',
            name='status_aktif',
        ),
        migrations.AddField(
            model_name='lotproduksi',
            name='lokasi_sekarang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lot_tersimpan', to='logistik.lokasi'),
        ),
        migrations.AddField(
            model_name='lotproduksi',
            name='qty_sisa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
