# Generated by Django 5.2.12 on 2026-03-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0002_alter_logtraceability_options_alter_lokasi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtraceability',
            name='qty_mutasi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
