# Generated by Django 5.2.12 on 2026-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0003_logtraceability_qty_mutasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotproduksi',
            name='qty_awal',
        ),
        migrations.RemoveField(
            model_name='lotproduksi',
            name='qty_sisa',
        ),
        migrations.AddField(
            model_name='lotproduksi',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kuantitas'),
            preserve_default=False,
        ),
    ]
