# Generated by Django 5.2.12 on 2026-04-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0004_remove_lotproduksi_qty_awal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotproduksi',
            name='lot_induk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_turunan', to='logistik.lotproduksi', verbose_name='Berasal dari Lot (Induk)'),
        ),
        migrations.AddField(
            model_name='lotproduksi',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Habis', 'Habis Diproses/Dilebur')], default='Aktif', max_length=20),
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='lokasi_asal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_keluar', to='logistik.lokasi'),
        ),
    ]
