# Generated by Django 5.2.12 on 2026-04-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0005_lotproduksi_lot_induk_lotproduksi_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('simbol', models.CharField(max_length=10)),
                ('rasio_ke_dasar', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Satuan',
            },
        ),
        migrations.AlterModelOptions(
            name='lotproduksi',
            options={},
        ),
        migrations.RemoveField(
            model_name='logtraceability',
            name='qty_mutasi',
        ),
        migrations.RemoveField(
            model_name='masterbarang',
            name='satuan',
        ),
        migrations.AddField(
            model_name='logtraceability',
            name='qty_hasil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logtraceability',
            name='qty_masuk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logtraceability',
            name='selisih_rendemen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='masterbarang',
            name='standar_rendemen',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Persentase hasil jadi yang diharapkan (0-100%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='lokasi_asal',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_keluar', to='logistik.lokasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='lokasi_sekarang',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lot_tersimpan', to='logistik.lokasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='lot_induk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_turunan', to='logistik.lotproduksi'),
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Habis', 'Habis Diproses')], default='Aktif', max_length=20),
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='tanggal_masuk',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='lotproduksi',
            name='satuan',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.RESTRICT, to='logistik.satuan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterbarang',
            name='satuan_standar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='logistik.satuan'),
        ),
    ]
