# Generated by Django 5.2.12 on 2026-04-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0006_satuan_alter_lotproduksi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbarang',
            name='satuan_standar',
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='lokasi_asal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_keluar', to='logistik.lokasi'),
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='lokasi_tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_masuk', to='logistik.lokasi'),
        ),
    ]
