# Generated by Django 5.2.12 on 2026-04-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0007_remove_masterbarang_satuan_standar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='satuan_standar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='logistik.satuan'),
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='satuan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='logistik.satuan'),
            preserve_default=False,
        ),
    ]
