# Generated by Django 5.2.12 on 2026-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0008_masterbarang_satuan_standar_alter_lotproduksi_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtraceability',
            name='qty_hasil',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='qty_masuk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='selisih_rendemen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
