# Generated by Django 5.2.12 on 2026-05-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0009_alter_logtraceability_qty_hasil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratJalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat_jalan', models.CharField(max_length=50, unique=True)),
                ('tujuan', models.CharField(max_length=200)),
                ('plat_nomor_truk', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lokasi',
            options={'ordering': ['id'], 'verbose_name_plural': 'Lokasi'},
        ),
        migrations.AlterModelOptions(
            name='masterbarang',
            options={'ordering': ['kode_barang'], 'verbose_name_plural': 'Master Barang'},
        ),
        migrations.AlterModelOptions(
            name='satuan',
            options={'ordering': ['id'], 'verbose_name_plural': 'Satuan'},
        ),
    ]
