# Generated by Django 5.2.12 on 2026-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0010_suratjalan_alter_lokasi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbarang',
            name='satuan_standar',
        ),
        migrations.RemoveField(
            model_name='lotproduksi',
            name='satuan',
        ),
        migrations.AlterModelOptions(
            name='lokasi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='masterbarang',
            options={},
        ),
        migrations.RenameField(
            model_name='lokasi',
            old_name='nama_lokasi',
            new_name='nama_area',
        ),
        migrations.RenameField(
            model_name='lokasi',
            old_name='jenis_lokasi',
            new_name='tipe_zona',
        ),
        migrations.RenameField(
            model_name='masterbarang',
            old_name='kode_barang',
            new_name='kode_sku',
        ),
        migrations.RenameField(
            model_name='masterbarang',
            old_name='nama_barang',
            new_name='nama_produk',
        ),
        migrations.RemoveField(
            model_name='masterbarang',
            name='standar_rendemen',
        ),
        migrations.AddField(
            model_name='lokasi',
            name='kapasitas_maksimal_palet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokasi',
            name='kode_lokasi',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterbarang',
            name='tipe_kemasan',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterbarang',
            name='umur_simpan_bulan',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Satuan',
        ),
    ]
