# Generated by Django 5.2.12 on 2026-05-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0011_remove_masterbarang_satuan_standar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtraceability',
            name='surat_jalan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistik.suratjalan'),
        ),
    ]
