# Generated by Django 5.2.12 on 2026-05-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0012_logtraceability_surat_jalan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotproduksi',
            name='batch_sap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
