# Generated by Django 5.2.12 on 2026-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0013_lotproduksi_batch_sap'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratjalan',
            name='target_palet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suratjalan',
            name='termuat_palet',
            field=models.IntegerField(default=0),
        ),
    ]
