# Generated by Django 5.2.12 on 2026-06-29 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0015_kavling_alter_logtraceability_lokasi_asal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtraceability',
            name='lokasi_asal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_keluar', to='logistik.lokasi'),
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='lokasi_tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_masuk', to='logistik.lokasi'),
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='lokasi_sekarang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lot_tersimpan', to='logistik.lokasi'),
        ),
        migrations.DeleteModel(
            name='Kavling',
        ),
    ]
