# Generated by Django 5.2.12 on 2026-06-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0016_alter_logtraceability_lokasi_asal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kavling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kavling', models.CharField(max_length=20, unique=True)),
                ('baris', models.CharField(max_length=10)),
                ('slot', models.CharField(max_length=10)),
                ('lokasi_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_kavling', to='logistik.lokasi')),
            ],
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='lokasi_asal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_keluar', to='logistik.kavling'),
        ),
        migrations.AlterField(
            model_name='logtraceability',
            name='lokasi_tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mutasi_masuk', to='logistik.kavling'),
        ),
        migrations.AlterField(
            model_name='lotproduksi',
            name='lokasi_sekarang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lot_tersimpan', to='logistik.kavling'),
        ),
    ]
